# Generated by Django 5.2.3 on 2025-07-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Resedencial'), ('comercial', 'Comercial')], max_length=20),
        ),
    ]
